name: realworld

on:
  pull_request:
  merge_group:

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  bundler:
    name: Realworld Bundler ${{ matrix.bundler.name }} on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-22.04 }

        ruby:
          - { name: ruby-2.6, value: 2.6.10 }
          - { name: ruby-2.7, value: 2.7.7 }
          - { name: ruby-3.0, value: 3.0.5 }
          - { name: ruby-3.1, value: 3.1.3 }
          - { name: ruby-3.2, value: 3.2.0 }

        bundler:
          - { name: 2, value: '' }
          - { name: 3, value: 3.0.0 }

        exclude:
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.6, value: 2.6.10 } }

        include:
          - { os: { name: MacOS, value: macos-12 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.7 } }
          - { os: { name: MacOS, value: macos-12 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.0, value: 3.0.5 } }
          - { os: { name: MacOS, value: macos-12 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.1, value: 3.1.3 } }
          - { os: { name: MacOS, value: macos-12 }, bundler: { name: 2, value: '' }, ruby: { name: ruby-3.2, value: 3.2.0 } }
    env:
      RGV: ..
      RUBYOPT: --disable-gems
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup ruby
        uses: ruby/setup-ruby@f60ef1e8084a2e64569f928c3f1cfac6c7e12ad7 # v1.137.2
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Prepare dependencies
        run: bin/rake spec:deps
        working-directory: ./bundler
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
        working-directory: ./bundler
      - name: Run Test
        run: bin/rake spec:realworld
        working-directory: ./bundler
      - name: Upload used cassettes as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cassettes-bundler-${{ matrix.bundler.name }}-${{ matrix.os.value }}-${{ matrix.ruby.name }}
          path: ./bundler/spec/support/artifice/used_cassettes.txt
    timeout-minutes: 20

  system_rubygems_bundler:
    name: Realworld Bundler ${{ matrix.bundler.name }} against system Rubygems (${{ matrix.ruby.name }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.6, value: 2.6.10 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-2.7, value: 2.7.7 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-3.0, value: 3.0.5 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-3.1, value: 3.1.3 } }
          - { bundler: { name: 2, value: '' }, ruby: { name: ruby-3.2, value: 3.2.0 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-2.7, value: 2.7.7 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-3.0, value: 3.0.5 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-3.1, value: 3.1.3 } }
          - { bundler: { name: 3, value: 3.0.0 }, ruby: { name: ruby-3.2, value: 3.2.0 } }
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup ruby
        uses: ruby/setup-ruby@f60ef1e8084a2e64569f928c3f1cfac6c7e12ad7 # v1.137.2
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Prepare dependencies
        run: bin/rake spec:deps
        working-directory: ./bundler
      - name: Replace version
        run: BUNDLER_SPEC_SUB_VERSION=${{ matrix.bundler.value }} bin/rake override_version
        if: matrix.bundler.value != ''
        working-directory: ./bundler
      - name: Run Test
        run: bin/rake spec:realworld
        working-directory: ./bundler
      - name: Upload used cassettes as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cassettes-system-rubygems-bundler-${{ matrix.bundler.name }}-${{ matrix.ruby.name }}
          path: ./bundler/spec/support/artifice/used_cassettes.txt
    timeout-minutes: 20

  check_unused_cassettes:
    name: Check unused cassettes
    needs: [bundler, system_rubygems_bundler]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup ruby
        uses: ruby/setup-ruby@f60ef1e8084a2e64569f928c3f1cfac6c7e12ad7 # v1.137.2
        with:
          ruby-version: 3.2.0
          bundler: none
      - name: Download all used cassettes as artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./bundler/spec/support/artifice/used_vcr_cassettes
      - name: Check unused cassettes
        run: bin/rake spec:realworld:check_unused_cassettes
        working-directory: ./bundler
