name: rubygems

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  rubygems:
    name: Rubygems on ${{ matrix.os.name }} (${{ matrix.ruby.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Ubuntu, value: ubuntu-22.04 }
          - { name: macOS, value: macos-14 }
          - { name: Windows, value: windows-2022 }

        ruby:
          - { name: "3.0", value: 3.0.7 }
          - { name: "3.1", value: 3.1.5 }
          - { name: "3.2", value: 3.2.4 }
          - { name: "3.3", value: 3.3.1 }

        include:
          - ruby: { name: jruby, value: jruby-9.4.6.0 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - ruby: { name: truffleruby, value: truffleruby-24.0.1 }
            os: { name: Ubuntu, value: ubuntu-22.04 }

          - os: { name: Windows, value: windows-2022 }
            ruby: { name: mswin, value: mswin }

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Setup ruby (Ubuntu/macOS)
        uses: ruby/setup-ruby@cacc9f1c0b3f4eb8a16a6bb0ed10897b43b9de49 # v1.176.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Configure bindgen
        shell: pwsh
        run: |
          echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
        if: matrix.ruby.name == 'mswin'
      - name: Install Dependencies
        run: rake setup
      - name: Run Test
        run: rake test
        if: matrix.ruby.name != 'truffleruby' && matrix.ruby.name != 'jruby'
      - name: Run Test isolatedly
        run: rake test:isolated
        if: matrix.ruby.name == '3.3' && matrix.os.name != 'Windows'
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug rake test
        if: startsWith(matrix.ruby.name, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" rake test
        if: matrix.ruby.name == 'truffleruby'

    timeout-minutes: 60
