name: truffleruby-bundler

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  truffleruby_bundler:
    name: Bundler (Truffleruby)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Setup ruby
        uses: ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa # v1.126.0
        with:
          ruby-version: truffleruby-22.3
          bundler: none
      - name: Prepare dependencies
        run: |
          bin/rake spec:parallel_deps
        working-directory: ./bundler
      - name: Run Test
        run: |
          bin/parallel_rspec --tag truffleruby_only --tag truffleruby
        working-directory: ./bundler
    timeout-minutes: 20
