name: windows-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.3

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows_rubygems:
    name: Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        cargo:
          - target: x86_64-pc-windows-gnu
            toolchain: stable
        ruby:
          - { name: "2.6", value: 2.6.10 }
          - { name: "2.7", value: 2.7.6 }
          - { name: "3.0", value: 3.0.4 }
          - { name: "3.1", value: 3.1.2 }
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Setup ruby
        uses: ruby/setup-ruby-pkgs@e5897b3f277d700f7b9e24b5819112945add74ff # v1.32.3
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
          mingw: clang
      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: ${{ matrix.cargo.toolchain }}-${{ matrix.cargo.target }}
          components: rustfmt
      - name: Print debugging info
        run: |
          echo "RbConfig::MAKEFILE_CONFIG"
          echo "========================="
          ruby -rrbconfig -ryaml -e 'puts YAML.dump(RbConfig::MAKEFILE_CONFIG)'
          echo "========================="

          echo "Machine info"
          echo "========================="
          uname -a
          echo "========================="
      - name: Install Dependencies and Run Test
        run: |
          rake setup
          rake test
        env:
          BUNDLE_WITHOUT: lint
    timeout-minutes: 25
